### R的基础操作

In [ ]:
1+2+3

In [2]:
x<-1

In [3]:
x

[1] 1

In [9]:
c(1, 2, 3, 4) + 1

[1] 2 3 4 5

In [4]:
b <- c(1,2,3,4,5,6,7,8,9,10,11,12)

In [5]:
length(b)

[1] 12

In [8]:
b[c(1,6,11)]

[1]  1  6 11

In [6]:
b > 5

[1] FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

In [7]:
b[b > 5]

[1]  6  7  8  9 10 11 12

### 矩阵
新建一个矩阵matrix()

In [13]:
m <- matrix(c(1:6), 2, 3)
m

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [14]:
n <- matrix(c(8:13), 2, 3)
n

[,1] [,2] [,3]
[1,] 8    10   12  
[2,] 9    11   13

矩阵的维度dim()
转置t()
提取元素[]
将两个矩阵合到一起rbind(), cbind()

In [12]:
dim(m)

[1] 2 3

In [15]:
t(m)#并没有覆盖原值

[,1] [,2]
[1,] 1    2   
[2,] 3    4   
[3,] 5    6

In [16]:
cbind(m, n)

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    3    5    8    10   12  
[2,] 2    4    6    9    11   13

In [17]:
rbind(m, n)

[,1] [,2] [,3]
[1,] 1     3    5  
[2,] 2     4    6  
[3,] 8    10   12  
[4,] 9    11   13

### 列表

数据的长度不一致或者类型不一致
提取元素[[]]或者$

In [18]:
l <- list(a = c(1, 2), b = 'apple')
l

$a
[1] 1 2

$b
[1] "apple"

In [20]:
l$a

[1] 1 2

In [21]:
l[[1]]

[1] 1 2

### 数据框

In [22]:
L3 <- LETTERS[1:3]
fac <- sample(L3, 10, replace = TRUE)#对L3进行十次随机抽样
d <- data.frame(x = 1, y = 1:10, fac = fac)

In [23]:
L3

[1] "A" "B" "C"

In [24]:
fac

[1] "A" "B" "C" "C" "B" "A" "B" "B" "B" "B"

In [25]:
d

x y  fac
1  1  1 A  
2  1  2 B  
3  1  3 C  
4  1  4 C  
5  1  5 B  
6  1  6 A  
7  1  7 B  
8  1  8 B  
9  1  9 B  
10 1 10 B

In [28]:
colnames(d)#d的列名

[1] "x"   "y"   "fac"

In [27]:
str(d)

'data.frame':	10 obs. of  3 variables:
 $ x  : num  1 1 1 1 1 1 1 1 1 1
 $ y  : int  1 2 3 4 5 6 7 8 9 10
 $ fac: Factor w/ 3 levels "A","B","C": 1 2 3 3 2 1 2 2 2 2


### 函数

In [29]:
f <- function(x, y) {
  z <- c(x + 1, y + 1)
  return(z)
}
f(1, 2)

[1] 2 3

In [30]:
f

function(x, y) {
  z <- c(x + 1, y + 1)
  return(z)
}

调入一个已经存在但是不在环境中的函数：source('函数保存的路径')

### The if condition
if (condition){
  do something
} else {
  do something
}

### 循环

In [31]:
x <- 1:10
for(i in x) {
  print(i^2)
}

[1] 1
[1] 4
[1] 9
[1] 16
[1] 25
[1] 36
[1] 49
[1] 64
[1] 81
[1] 100


### 小练习
输入一个向量，输出列表

In [38]:
MySummary <- function(x){
    mean<-mean(x)
    var<-var(x)
    len<-length(x)
    max<-max(x)
    min<-min(x)    
    result <- list(mean = mean, var=var,len=len,max=max,min=min)
}
x=c(1, 2, 3)
result<-MySummary(x)
result

$mean
[1] 2

$var
[1] 1

$len
[1] 3

$max
[1] 3

$min
[1] 1

### R的编程规范

1. 文件名、变量名、函数名（一般是动词开头）要有意义  
2. 空格  
3. 习惯换行  
4. 大括号
    1. 左边的大括号一般不会单独一行，但是右边的会单独一行。  
    2. 主体部分要换号，且要缩进（tab）。 
5. Rstudio的code里面Reindent line（Ctrl+R）自动加缩进

 

### Some nice R tips

In [64]:
install.packages('formatR',repos = "http://cran.us.r-project.org")

package 'formatR' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Administrator\AppData\Local\Temp\RtmpQjON2X\downloaded_packages


In [65]:
library("formatR")

Warning message:
"package 'formatR' was built under R version 3.5.3"

已经安装了包，但是不知道auto.arima在哪个包里

In [44]:
??auto.arima
#在Rstudio里速度快一点

starting httpd help server ... done


In [ ]:
library(sos)
findFn("arima")##输出所有和arima相关的函数
RSiteSearch("arima")

### 小练习
输出ax^2+bx+c=0的解

In [63]:
solvefun <- function(a,b,c){
    if(a == 0){
        return <- list(x=-c/b)
    }else{
        issolved = b * b - 4 * a * c
        if(issolved < 0){
            print("无解")   
        }else{
            if(issolved > 0){
                x1 = (-b + sqrt(issolved)) / 2*a
                x2 = (-b - sqrt(issolved)) / 2*a
                return <- list(x1=x1,x2=x2)
            }else{
                return <- list(x=-b / 2*a)
            }
        }
    }
}
result=solvefun(0,-2,1)
result

$x
[1] 0.5

要判断a=0，b=0，c=0的情况